version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: smallstep:master    # Required. Must be in the same fork network.
    mergeMethod: merge 